# Generated by Django 3.2 on 2021-05-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('realtime_price', models.IntegerField()),
                ('moving_average', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('p', 'price'), ('v', 'volume'), ('m', 'moving_average')], max_length=16)),
                ('smaller_or_greater', models.CharField(choices=[('g', 'greater_than'), ('s', 'smaller_than')], max_length=16)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
