# Generated by Django 3.2 on 2021-05-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radarcxapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
