# Generated by Django 3.2 on 2021-05-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radarcxapp', '0004_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='type',
            field=models.CharField(choices=[('realtime_price', 'realtime_price'), ('volume', 'volume'), ('moving_average', 'moving_average')], max_length=16),
        ),
    ]
