# Generated by Django 3.2 on 2021-05-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radarcxapp', '0005_alter_condition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='type',
            field=models.CharField(choices=[('realtime_price', 'realtime_price'), ('volume', 'volume'), ('moving_average', 'moving_average')], default='realtime_price', max_length=16),
        ),
    ]
