# Generated by Django 3.2 on 2021-05-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radarcxapp', '0010_alter_condition_smaller_or_greater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='moving_average',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='realtime_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='condition',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='condition',
            name='smaller_or_greater',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='condition',
            name='type',
            field=models.CharField(max_length=16),
        ),
    ]
