# Generated by Django 3.2 on 2021-05-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radarcxapp', '0011_auto_20210522_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='moving_average',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coin',
            name='realtime_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coin',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
