# Generated by Django 3.2 on 2021-06-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radarcxapp', '0013_condition_triggered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='realtime_price',
            field=models.FloatField(default=0),
        ),
    ]
